#!/usr/bin/env python3
"""v1840 LANGUAGES — rebuilds every generated translation file from the sources here.

  python scripts/i18n/build_i18n.py

Sources (edit these):
  source_app.json      {English: {es, ko, ja, zh}} for the app (golf-app.html / www)
  source_site.json     same, for officialbadgolf.com (marketing, support, legal)
  overrides.json       hand fixes; wins over source_app.json
  native_strings.json  iOS permission prompts, Live Activity labels, AR screen labels
  GLOSSARY.md          the translators' rulebook (game names stay English, units, etc.)

Writes (do not hand-edit):
  i18n/<lang>.json, www/i18n/<lang>.json     app dictionaries ("x" exact, "p" patterns)
  site/i18n/<lang>.json                       website dictionaries
  ios/App/App/<lang>.lproj/InfoPlist.strings
  ios/App/BadGolfWidgets/<lang>.lproj/Localizable.strings

To add strings: put English keys with all four languages into overrides.json (or ask
Claude to "translate i18n/MISSING.txt"), then run this script and commit.
"""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
LANGS = ['es', 'ko', 'ja', 'zh']
PH = re.compile(r'\{\d+\}')


def load(name):
    p = os.path.join(HERE, name)
    return json.load(open(p, encoding='utf-8')) if os.path.exists(p) else {}


def write_json(path, obj):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(obj, f, ensure_ascii=False, separators=(',', ':'))


def app_dicts():
    m = load('source_app.json')
    ov = load('overrides.json')
    for k, v in ov.items():
        m.setdefault(k, {}).update(v)
    for L in LANGS:
        x, p = {}, []
        for k, v in m.items():
            t = v.get(L)
            if not t or (t == k and k not in ov):   # v1903 (audit #2 #34): an override pinned to English (a game name) stays in the dictionary so no pattern can rewrite it
                continue
            (p.append([k, t]) if PH.search(k) else x.__setitem__(k, t))
        p.sort(key=lambda a: -len(PH.sub('', a[0])))
        d = {'lang': L, 'n': len(x) + len(p), 'x': x, 'p': p}
        for base in ('i18n', os.path.join('www', 'i18n')):
            write_json(os.path.join(ROOT, base, L + '.json'), d)
        print(f'app {L}: {len(x)} strings + {len(p)} patterns')


def site_dicts():
    m = load('source_site.json')
    for L in LANGS:
        d = {k: v[L] for k, v in m.items() if v.get(L) and v[L] != k}
        p = os.path.join(ROOT, 'site', 'i18n', L + '.json')
        os.makedirs(os.path.dirname(p), exist_ok=True)
        with open(p, 'w', encoding='utf-8', newline='\n') as f:
            json.dump(d, f, ensure_ascii=False, indent=0)
        print(f'site {L}: {len(d)} strings')


def ios_strings():
    n = load('native_strings.json')
    esc = lambda s: s.replace('\\', '\\\\').replace('"', '\\"')
    for L in ['en', 'es', 'ko', 'ja', 'zh-Hans']:
        d = os.path.join(ROOT, 'ios', 'App', 'App', L + '.lproj')
        os.makedirs(d, exist_ok=True)
        lines = ['/* v1840 languages - generated by scripts/i18n/build_i18n.py from native_strings.json. Edit that file, not this one. */']
        lines += [f'"{k}" = "{esc(v[L])}";' for k, v in n.get('infoplist', {}).items()]
        open(os.path.join(d, 'InfoPlist.strings'), 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
        if L == 'en':
            continue
        d = os.path.join(ROOT, 'ios', 'App', 'BadGolfWidgets', L + '.lproj')
        os.makedirs(d, exist_ok=True)
        lines = ['/* v1840 languages - Live Activity labels. Generated by scripts/i18n/build_i18n.py. */']
        lines += [f'"{esc(k)}" = "{esc(v[L])}";' for k, v in n.get('widget', {}).items()]
        open(os.path.join(d, 'Localizable.strings'), 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
    print('ios strings: InfoPlist.strings x5, Live Activity Localizable.strings x4')


if __name__ == '__main__':
    app_dicts()
    site_dicts()
    ios_strings()
